### ISSUE TITLE
Stylelint V3 requires plugin to expose it's self. The plugin is not doing this.

### ISSUE THREAD

**Issue by denOldTimer** [prettier/stylelint-prettier#165]
**What version of `stylelint`, `prettier` and `stylelint-prettier` are you using?**
```json
"stylelint": "^13.12.0",
"stylelint-prettier": "^1.2.0",
```
**Please paste any applicable config files that you're using (e.g. `.prettierrc` or `.stylelintrc` files)**
```javascript
// stylelint.config.js
module.exports = {
  extends: [
    //"stylelint-config-sass-guidelines",
    //"stylelint-config-recommended",
    //"stylelint-config-recommended-scss",
    "stylelint-config-twbs-bootstrap/scss",
    //"stylelint-prettier/recommended",
  ],
  plugins: ["prettier-stylelint"],
  defaultSeverity: "warning",
  rules: {
    "prettier/prettier": true,
   }
}
```
**What source code are you linting?**
`SCSS `

**What did you expect to happen?**
Normal working linting

**What actually happened?**
![stylelint-prettier-issue](https://user-images.githubusercontent.com/51490799/111180192-126e7f80-85ad-11eb-850b-a5fca5f06541.png)

**Extra info **
`npm i -D stylelint-prettier` renames it's self to `prettier-stylelint`
`plugins: ["stylelint-prettier]  ` --> gives an error plugin not found
`plugins: ["prettier-stylelint]  ` --> gives the error mentioned above

![stylelint-prettier-node_modules](https://user-images.githubusercontent.com/51490799/111180926-c2dc8380-85ad-11eb-835a-d12d5d378263.png)

`plugins: ["stylelint-prettier]  ` --> `npm run fix-styles` --> 

![stylelint-config](https://user-images.githubusercontent.com/51490799/111184601-6713f980-85b1-11eb-8a5d-3fb8e9f4bd26.png)

![stylelint-prettier-scripts-error](https://user-images.githubusercontent.com/51490799/111184172-fc62be00-85b0-11eb-912b-81bf9e2243ce.png)
![stylelint-prettier-scripts](https://user-images.githubusercontent.com/51490799/111184228-0b497080-85b1-11eb-8373-fc930ee9b80f.png)

**Comment by BPScott** [comment]
There's two, (confusingly named) packages:

- [`stylelint-prettier`](https://www.npmjs.com/package/stylelint-prettier)  - This package. It's stylelint-plugin that runs prettier as a stylelint rule.
- [`prettier-stylelint`](https://www.npmjs.com/package/prettier-stylelint) - A package that exposes a cli command that runs prettier then stylelint over a set of files.

Having `plugins: ["prettier-stylelint"]` in your package.json won't work because that package isn't a prettier plugin. If you want to run prettier as a stylelint rule you need to have `plugins: ["stylelint-prettier]`.


> npm i -D stylelint-prettier renames it's self to prettier-stylelint

This seems very bizare and has nothing to do with this project. Are you sure you're not accidentally installing both prettier-stylelint and stylelint-prettier and getting confused?


---

I'm not sure what you want to do here? Using prettier-stylelint and stylelint-prettier are mutually exclusive approaches. There's no point to using prettier-stylelint  to run your files through prettier and then through stylelint if you're also configuring stylelint to enable the stylelint-prettier plugin which will run prettier over your files *as part* of running stylelint.

**Comment by denOldTimer** [comment]
@BPScott 
Hi there.
1. I've created a project and I'm using webpack to run stylielint
BUT my stylelint.config.js is not in the root 
![project-structure](https://user-images.githubusercontent.com/51490799/111406914-5fe50c80-86d3-11eb-8235-77617b268dbc.png)

2. I've got prettier and prettier+ extensions installed in VScode

Reason for step 1 is I want to public free the project and thus have stylint run when webpack runs via npm run.

Reason for step 2: 
 * a Prettier doesnot allow stylelint integration, the option is in the default settings thus Prettier+
 * b. Is to have stylelint run evertime I save a document and Prettier+ format its.

I've gotten b to work.
But a. doesn't want to work.
It keeps asking me for a ConfigBaseDir

![plugins](https://user-images.githubusercontent.com/51490799/111407845-9a9b7480-86d4-11eb-97d3-2e8e5f8a0e12.png)

What I want:
a. stylelint to work with vscode linting while I type and onSave formatting my scss
b. stylelint to work with webpack

thus now I've installed so much that it's gotten a bit muddled.
But I think I got it to work.

## HOLY MACKREL I GOT THE DAM THING TO WORK


### VSCODE
On vscode install two extensions prettier and prettier+ and make prettier the default formatter for scss.
Then in your workspace settings or in your project root create a folder '.vscode' and add a file stettings.json
then add the following code
```json
{
    "stylelint.configFile": "./resources/webpack/stylelint.config.js",
    "editor.codeActionsOnSave": {
        "source.fixAll": true,
        "source.fixAll.stylelint": true
    },
    "editor.tabSize": 2,
    "prettier.stylelintIntegration": true
}
``
you need prettier+ for the last part `"prettier.styleintegration" : true` to get it working

### WEBPACK

Then in your project install via  `npm   i -D stylelint-scss  stylelint  stylelint-prettier`
and as a standard guide I'm testing that of bootstrap `stylelint-config-twbs-bootstrap` 
and create a config file and add the following code
```javascript
module.exports = {
  extends: [
    //"stylelint-config-sass-guidelines",
    //"stylelint-config-recommended",
    //"stylelint-config-recommended-scss",
    "stylelint-config-twbs-bootstrap/scss",
    //"stylelint-prettier/recommended",
  ],
  plugins: ["stylelint-scss", "stylelint-prettier"],
  defaultSeverity: "warning",
  rules: {
    "prettier/prettier": true,
  },
};
```
### WHAT CHANGED SINCE YESTERDAY
plugins: ["stylelint-scss", "stylelint-prettier"],
I added stylelint-scss to my plugins list.
It was staring me in my face.

yesterday 
plugins: ["stylelint-prettier"],
today
plugins: ["stylelint-scss", "stylelint-prettier"],

I totally for got that plugins is an array.

## BUT stil got a question
How does one work with stylelint option : configBasdir
```javascript
const StyleLintPlugin = new _StyleLintPlugin({
  configFile: path.resolve(__dirname, "stylelint.config.js"),
  //configBasedir: path.resolve(__dirname, "./node_modules/"),
  context: path.resolve(__dirname, "../src/scss"),
  files: "**/*.scss",
  syntax: "scss",
});

``` 


So vscode and stylelint open your build in terminal and go to the tap **problems** and you'll get a list of errors for your current document created by pretiier & stylelint.
And when I run webpack in the **terminal** I get an error list created by webpack and stylelint

![stylelint-error-list-prettier](https://user-images.githubusercontent.com/51490799/111411452-e2bd9580-86da-11eb-8bc8-fa89db5eca96.png)
![stylelint-error-list-webpack](https://user-images.githubusercontent.com/51490799/111411461-e6511c80-86da-11eb-833a-9b4ea718d1a6.png)

**Comment by BPScott** [comment]
> How does one work with stylelint option : configBasdir

This seems like a concern of the `stylelint` rather than this plugin.

It feels like you're inventing problems for yourself by not placing your stylelint.config.js in the root of your repository. I would expect whatever webpack plugin you're using to be able to handle reading from a stylelint config file at the base of your repository. My advice would be to put your styllint config in your root and make sure you can run `stylelint` from the command line in the root of  your project, and then most other tools should fall into place.

I'm going to close this issue as it is no longer an issue with stylelint-prettier, but an issue with however you're configuring your project.
