### ISSUE TITLE
No such file

### ISSUE THREAD

**Issue by maystrenkoYurii** [prettier/stylelint-prettier#4]
Error: ENOENT: no such file or directory, scandir   'C:\:\Users\yura\WebstormProjects\apartament-web-ui\src\assets\fonts'    error in C:\:\Users Windows 10 WebStorm `module.exports = {
  "plugins": ["stylelint-prettier"],
  "rules": {
    "prettier/prettier": true
  }
};
`
![default](https://user-images.githubusercontent.com/23016311/45628955-f2be7500-ba9d-11e8-8f0e-b2426d8a6f92.PNG)

**Comment by BPScott** [comment]
`C:\:\Users\....` does not appear to be a valid path on Windows, note the additional `:\`. `C:\Users\...` would be valid. This seems to be a problem with the Webstorm plugin you are using as it is building paths out incorrectly.

 Can you recreate this problem on the command line, with a valid windows path?

**Comment by BPScott** [comment]
Closing this due to no response

**Comment by alexnlong** [comment]
I also have this issue, except it's in IDEA Ultimate. I'm using the built-in Stylelint feature, and it gives the same error.
![intellij-stylelint_enoent_error](https://user-images.githubusercontent.com/1895634/48592348-9943bc80-e90d-11e8-87f8-911fedccadb1.png)

I have Node.js v8.9.4, and Stylelint v7.10.1

**Comment by alexnlong** [comment]
The only invalid part of the path is the extra "\:". It doesn't reproduce the error with the valid path, but it still does not work as expected. Running the same command with the absolute path to the file printed the help information of Stylelint with no error in sight.

**Comment by alexnlong** [comment]
Ok, I think I found out what's up with my particular issue. Intellij's built-in functionality of Stylelint won't play nice with stylelint-prettier when the .stylelintrc is set to:
` {
  "extends": ["stylelint-prettier/recommended"]
} `
So sad. Intellij (and I also assume the other IDEs) has Prettier built in, too, and I would like to use them both. I figured that I needed this plugin to have them work together.

**Comment by BPScott** [comment]
> The only invalid part of the path is the extra "\:". It doesn't reproduce the error with the valid path, but it still does not work as expected. Running the same command with the absolute path to the file printed the help information of Stylelint with no error in sight.

I don't know the internals of the Jetbrains' stylelint plugin but it using `--stdin-filename` suggests that it expects the contents of a file to be piped into stylelint using `stdin`. If you don't specify any code to lint in `stdin` then stylelint will just print usage information.

> Ok, I think I found out what's up with my particular issue. Intellij's built-in functionality of Stylelint won't play nice with stylelint-prettier when the .stylelintrc is set to:
{ "extends": ["stylelint-prettier/recommended"] }

This is because stylelint-prettier uses the filename that was provided to stylelint and tries to get the prettier config for that file (so it knows if it should use double or single quotes etc). However in your case the filename is invalid which causes a crash. The fix for this is that your IDE should call stylelint with a valid file path.
